version: 0.2

env:
  variables:
    RDS_HOSTNAME: "localhost"
    RDS_DB_NAME: "rafr"
    RDS_USERNAME: "root"
    RDS_PASSWORD: "password"
    NODE_ENV: "development"

phases:
  install:
    commands:
      - cd ./API/
      - npm install
      - cd ../
