version: 0.2

env:
  variables:
    RAFR_DB_HOST=localhost
    RAFR_DB_NAME=rafr
    RAFR_DB_USERNAME=root
    RAFR_DB_PASSWORD=password
    NODE_ENV=development

phases:
  install:
    - cd ./API/
    - npm install
    - cd ../
  pre_build:
    - cd ./API/
    - mysql -u root -ppassword < ./models/schema.sql
    - cd ../
  build:
    - cd ./API/
    - npm tun generate-models
    - cd ../
  post_build:
    - cd ./API/
    - npm start
