branch-defaults:
  add-code-pipeline-build:
    environment: rafr-env
    group_suffix: null
global:
  application_name: ReallyAwesomeFeatureRequests
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
