language: node_js
node_js:
  - "7"
  - "node"
install:
  - npm i
env:
  - RAFR_DB_HOST=localhost RAFR_DB_NAME=rafr NODE_ENV=development
  - RAFR_DB_HOST=localhost RAFR_DB_NAME=rafr NODE_ENV=production