version: '3'
services:
  db:
    image: mysql
    networks:
      - rafrapp
    ports:
      - 3306:3300
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
  app:
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - rafrapp
    environment:
      MYSQL_PORT: 3300
#    deploy:
#      mode: replicated
#      replicas: 2
networks:
  rafrapp:
